### ISSUE TITLE
Randomly stops working when reopening the app

### ISSUE THREAD

**Issue by ryanidk** [maheshmnj/searchfield#62] opened 2022-11-03 01:07 UTC
**Describe the bug**
When I close the app thru the app switcher in release mode and reopen it from the home screen, the search field stops working. When I click it and type something (e.g. "Mexico") nothing shows up.

**To Reproduce**
1. Force close app thru app switcher
2. Reopen app
3. Click on search bar

**Expected behavior**
I should be able to search after force closing app

**Actual behavior**
I can't search

**Code sample**
<details>
<summary>Show code sample</summary>

```dart  
SearchField(
                controller: numController,
                suggestions:
                    cnt.map((e) => SearchFieldListItem(e)).toList(),
                suggestionState: Suggestion.hidden,
                searchStyle: TextStyle(fontSize: 18),
                onSuggestionTap: _getInfo,
                searchInputDecoration: InputDecoration(
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(10),
                  ),
                  labelText: "Search",
                  suffixIcon: IconButton(
                      onPressed: () => numController.clear(),
                      icon: Icon(Icons.clear)),
                  contentPadding: EdgeInsets.symmetric(horizontal: 10),
                ),
                maxSuggestionsInViewPort: 5,
                itemHeight: 55,
                suggestionsDecoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(10),
                    border: Border.all(
                        color: Colors.red,
                        style: BorderStyle.solid,
                        width: 2.0)),
                suggestionStyle: TextStyle(fontSize: 18),
                suggestionItemDecoration: BoxDecoration(
                  border: Border(
                      left: BorderSide(width: 10.0, color: Colors.transparent),
                      top: BorderSide(width: 5, color: Colors.transparent),
                      bottom: BorderSide(width: 5, color: Colors.transparent)),
                ),
              ),
```
</details>

**Additional context**
This is very random

**Comment by maheshmnj** [comment] 2023-02-01 17:05
Hello @ryanidk, thanks for reporting the issue, and sorry for the delay. Can you please verify if `onChanged`of a TextFormfield triggers, when you try to reproduce the issue (Without this package)?

```dart
TextFormfield(
onChanged: (x){
   // is this called? 
 }
)
```

**Comment by ryanidk** [comment] 2023-02-01 21:09
I don't think its triggering, I don't see

**Comment by maheshmnj** [comment] 2023-02-04 01:39
Thanks for the update @ryanidk,  In that case I would suggest filing the issue in the [official flutter repo](https://github.com/flutter/flutter)

**Comment by maheshmnj** [comment] 2023-02-23 05:50
If you file the issue, then please leave a link to the issue here so that we can track the progress about the issue here.

**Comment by maheshmnj** [comment] 2023-05-02 22:22
@ryanidk Since there has been no update from your side, I will close this issue for now. Incase you still think this is an issue with this package, feel free to write back and I will reopen it.

Thank you.

**Closed by maheshmnj** 2023-05-02 22:22 UTC
Labels: waiting for author, in triage
