### ISSUE TITLE
Tapping/Touching the suggestions list while it scrolls closes it 

### ISSUE THREAD

**Issue by Groseuros** [maheshmnj/searchfield#141] opened 2024-05-27 13:43 UTC
**Describe the bug**
Tapping/Touching the suggestions list while it scrolls (in order to select an item or to scroll further) closes it.
Tapping/Touching the suggestions list while onScroll events are fired calls onTapOutside.

[x] By clicking this checkbox, I confirm I am using the latest version of the package found on [pub.dev/searchfield](https://pub.dev/packages/searchfield)

**Expected behavior**
Tapping/Touching the suggestions list while it scrolls doesn't close it

**Actual behavior**
Tapping/Touching the suggestions list while it scrolls closes it

**Comment by maheshmnj** [comment] 2024-05-27 20:27
Hello @Groseuros, Thanks for filing the issue.
This looks like a duplicate of https://github.com/maheshmnj/searchfield/issues/137, I intend to fix that issue this week Please follow up on that issue for further updates. 

Closing as duplicate, Feel free to reopen the issue if I am mistaken..

**Closed by maheshmnj** 2024-05-27 20:27 UTC
Labels: in triage
