### ISSUE TITLE
Suggestions remain after leaving page/screen

### ISSUE THREAD

**Issue by jpalmer42** [maheshmnj/searchfield#76] opened 2023-03-21 16:51 UTC
**Suggestions Box remains after leaving the screen**
When "hasOverlay" is true (default) and the user does not select an item, but leaves the screen (pop), the Suggestion Box remains on screen.

**Expected behavior**
Suggestion Box to be removed.

**Actual behavior**
Suggestion Box remains on screen.
What you actually saw instead of the expected behavior.

**Screenshots**
![image](https://user-images.githubusercontent.com/19267731/226679601-551279f4-a80c-4f5d-8d6d-f11d1c6fb924.png)

**Code sample**

```dart  
SearchField<ToadEstablishment>(
            hasOverlay: true,
            suggestions: establishments
                .map(
                  (e) => SearchFieldListItem<ToadEstablishment>(
                    (e.name ?? ''),
                    item: e,
                  ),
                )
                .toList(),
            suggestionState: Suggestion.expand,
            textInputAction: TextInputAction.next,
            controller: tecSourceSearch,
            focusNode: widget.focusNodes['puSearch'],
            searchInputDecoration: InputDecoration(
              contentPadding: Constants.doublePadding,
              border: InputBorder.none,
              hintText: 'Search Establishment',
              suffixIcon: IconButton(
                tooltip: 'Restore',
                icon: const Icon(Icons.restore),
                onPressed: () => tecSourceSearch.cancel(),
              ),
            ),
            maxSuggestionsInViewPort: 4,
            itemHeight: 50,
            onSuggestionTap: (value) {
              setState(() {
                widget.toadItem.establishment = value.item!;
                tecSourcePhone.text = formatPhone(value.item!.phone);
                tecSourceAddress.text = value.item!.formattedAddress!;
                widget.focusNodes['puDriver']?.requestFocus();
              });
            },
            suggestionAction: SuggestionAction.next,
          ),
```
</details>

**Additional context**
N/A

**Comment by maheshmnj** [comment] 2023-03-22 01:14
Hi @jpalmer42, I tried the [the example app](https://github.com/maheshmnj/searchfield/blob/master/example/lib/country_search.dart) and it seems to work fine, Can you share a minimum and complete sample code which I can directly run and reproduce the issue?

**Comment by TomJFox** [comment] 2023-04-18 22:59
@maheshmnj I am seeing the same issue even after using version 0.7.6.  But only when running on iOS or Android.  On a web app this runs fine.  Have you tried this on a iOS or Android device?

**Comment by maheshmnj** [comment] 2023-04-21 07:52
> @maheshmnj I am seeing the same issue even after using version 0.7.6. But only when running on iOS or Android. On a web app this runs fine. Have you tried this on a iOS or Android device?

@TomJFox Yes, Does the issue reproduce with this [example app](https://github.com/maheshmnj/searchfield/blob/master/example/lib/country_search.dart)? If not can you share a minimal and complete reproducible code sample?

**Comment by TomJFox** [comment] 2023-04-26 22:09
@maheshmnj Thanks for sharing this...

I was unable to reproduce this with this example.  I was able to compare to the example you shared and found that I had not passed the focusNode to the SearchField. 

Would adding a remove call if _overlayEntry was mounted to dispose() also help perhaps?  I have added this locally before adding the focusNode, and it seems to have improved the problem I was seeing.

```
  @override
  void dispose() {
    suggestionStream.close();
    _scrollController.dispose();
    if (widget.controller == null) {
      searchController!.dispose();
    }
    if (widget.focusNode == null) {
      _focus!.dispose();
    }

    // 3 lines added to remove overlay if disposed while mounted
    if (_overlayEntry != null && _overlayEntry!.mounted) {  
      _overlayEntry?.remove();
    }

    super.dispose();
  }

```

**Comment by maheshmnj** [comment] 2023-04-27 02:57
Thanks for the update will take a look at it shortly.

**Comment by maheshmnj** [comment] 2023-04-27 20:52
@TomJFox Is it possible for you to share a minimal and complete code sample? Unfortunately, I was not able to reproduce the issue on IOS or Android with or without focusNode. 
And we should definitely remove the overlay onDispose

**Comment by maheshmnj** [comment] 2023-04-27 20:58
I have published [v0.7.7](https://pub.dev/packages/searchfield/changelog) with the fix Please check and see if that resolves the issue.

**Comment by TomJFox** [comment] 2023-04-27 21:54
@maheshmnj  I have not seen this again.  Thanks for the update!  Hopefully @jpalmer42 has also had some success.

**Comment by maheshmnj** [comment] 2023-07-05 15:27
Closing as fixed! Incase anyone still encounters this issue Please feel free to write back and I would be happy to investigate.

**Closed by maheshmnj** 2023-07-05 15:27 UTC
Labels: waiting for author, in triage
