### ISSUE TITLE
This widget has been unmounted, so the State no longer has a context (and should be considered defunct). 

### ISSUE THREAD

**Issue by anais6** [maheshmnj/searchfield#17] opened 2022-02-15 16:45 UTC
Hi.

I have a ListView.builder that i use to build a list of search fields. when i add several  fields, and add information in one of them
and then try to remove one of them from the list i get "This widget has been unmounted, so the State no longer has a context (and should be considered defunct)."

so if i understand correctly, since the exception shows the searchfield component i assume it's related to this component, that somewhere in the code there is a setState() function called without checking if it's mounted.

first of all.. am i correct assuming that? and is there a work-around for now? thanks

this is the full exception:

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building StreamBuilder<List<String?>?>(dirty, state: _StreamBuilderBaseState<List<String?>?, AsyncSnapshot<List<String?>?>>#19e19):
This widget has been unmounted, so the State no longer has a context (and should be considered defunct). 

Consider canceling any active work during "dispose" or using the "mounted" getter to determine if the State is still active.
The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///C:/Users/attia/Documents/appointments/appointments-client/lib/main.dart:52:12
When the exception was thrown, this was the stack: 
#0      State.context.<anonymous closure> (package:flutter/src/widgets/framework.dart:942:9)
#1      State.context (package:flutter/src/widgets/framework.dart:948:6)
#2      _SearchFieldState.getYOffset (package:searchfield/src/searchfield.dart:371:32)
#3      _SearchFieldState._createOverlay.<anonymous closure>.<anonymous closure> (package:searchfield/src/searchfield.dart:404:29)
#4      StreamBuilder.build (package:flutter/src/widgets/async.dart:442:81)
#5      _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:124:48)
#6      StatefulElement.build (package:flutter/src/widgets/framework.dart:4870:27)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4754:15)
#8      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#9      Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#10     StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#13     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#14     ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#17     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#19     StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#22     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#23     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#24     StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#26     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5845:32)
#27     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6445:17)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#30     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#31     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#32     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#33     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#34     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#35     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#36     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#37     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#41     _invoke (dart:ui/hooks.dart:151:10)
#42     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#43     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
====================================================================================================

```

**Comment by maheshmnj** [comment] 2022-02-23 03:59
Hi @anais6, Thanks for filing the issue. Would it be possible for you to share a minimal reproducible code?  

> so if i understand correctly, since the exception shows the searchfield component i assume it's related to this component, that somewhere in the code there is a setState() function called without checking if it's mounted.

I think you are right, I will need to check it.

**Comment by maheshmnj** [comment] 2022-02-23 04:00
Update: There has been a new release two days back `v0.6.1` can you please give it a try and see if that helps fix the issue?

If you still encounter it please share a  [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to better address the issue

**Comment by amirthapa** [comment] 2022-05-26 10:32
In My case ### **hasOverlay = false**  solved the issue.

**Comment by AlvaroG2** [comment] 2022-06-03 10:25
> In My case ### **hasOverlay = false** solved the issue.

Thanks <3

**Comment by maheshmnj** [comment] 2022-06-04 07:56
@AlvaroG2 Is this issue reproducible with latest version of the package? if so can you please share a minimal code sample so that I can fix it?

**Comment by eponcehenriquez** [comment] 2022-06-24 15:56
Just to help the community, I use the following version and it throws the same error:

searchfield:
     dependency: "direct main"
     description:
       name: searchfield
       url: "https://pub.dartlang.org"
     source: hosted
     version: "0.6.5"

The solution was to add hasOverlay: false and it was fixed.
Below I attach my code where I use.

`Container(
                        padding: EdgeInsets.fromLTRB(20, 10, 20, 0),
                        child: SearchField(
                          hasOverlay: false,
                          controller: selectLabor,
                          maxSuggestionsInViewPort: 8,
                          searchStyle: TextStyle(
                            fontSize: 12,
                            color: Colors.black.withOpacity(0.8),
                          ),
                          hint: 'Seleccionar Labor',
                          searchInputDecoration: InputDecoration(
                              contentPadding: EdgeInsets.fromLTRB(10, 0, 0, 0),
                              enabledBorder: OutlineInputBorder(
                                  borderSide: BorderSide(
                                      color: Colors.blueGrey.shade200,
                                      width: 1),
                                  borderRadius: BorderRadius.circular(10)),
                              focusedBorder: OutlineInputBorder(
                                  borderSide: BorderSide(
                                      color: Colors.blue.withOpacity(0.8),
                                      width: 2),
                                  borderRadius: BorderRadius.circular(10))),
                          suggestions: ordenesService.selectOrden.listadolabores
                              .map((e) => SearchFieldListItem(
                                    e.labores.descripcion,
                                    item: e.labores.id,
                                  ))
                              .toList(),
                          validator: (x) {
                            var laborEncontrada = false;
                            int i = 0;
                            while (i <
                                ordenesService
                                    .selectOrden.listadolabores.length) {
                              String nombreLabor = ordenesService.selectOrden
                                  .listadolabores[i].labores.descripcion;
                              if (nombreLabor == x) {
                                laborEncontrada = true;
                                break;
                              }
                              i++;
                            }
                            if (!laborEncontrada || x!.isEmpty) {
                              return 'Por favor selecciona una Labor';
                            }
                            return null;
                          },
                          onSuggestionTap: (SearchFieldListItem x) {
                            idLabor = x.item;
                            laborSeleccionada = x.searchKey;
                          },
                        ),
                      ),`

**Comment by eponcehenriquez** [comment] 2022-06-24 16:05
Just to help the community, I use the following version and it throws the same error:

searchfield:
dependency: "direct main"
description:
name: searchfield
url: "https://pub.dartlang.org/"
source: hosted
version: "0.6.5"

The solution was to add hasOverlay: false and it was fixed.
Below I attach my code where I use.
![carbon](https://user-images.githubusercontent.com/3433466/175574150-e3917830-6724-4ae8-8ecb-660337ae444a.png)

**Comment by fruitbite** [comment] 2022-07-29 12:05
if I disable hasOverlay then it overflows bottom insets and is not usable for me atleast

**Comment by maheshmnj** [comment] 2022-07-29 12:54
Can you please share a code sample in the form of text so that I can take a look?

**Comment by fruitbite** [comment] 2022-07-29 13:14
```dart
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:searchfield/searchfield.dart';

class SearchBar extends StatefulWidget {
  const SearchBar({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<SearchBar> createState() => _SearchBarState();
}

class _SearchBarState extends State<SearchBar> {
  final TextEditingController _searchController = TextEditingController();

  @override
  void initState() {
    final foodCubit = BlocProvider.of<SearchBarCubit>(context);

    foodCubit.getAllItems();
    super.initState();
  }

  @override
  void dispose() {
    _searchController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<SearchBarCubit, SearchBarState>(
      builder: (context, state) {
        return Container(
            height: 50,
            padding: const EdgeInsets.symmetric(horizontal: 10),
            margin: const EdgeInsets.symmetric(horizontal: 20),
            width: double.infinity,
            decoration: const ShapeDecoration(
              shape: StadiumBorder(),
              color: AppColor.placeholderBg,
            ),
            child: SearchField(
              suggestions: state.foodList
                  .map((item) => SearchFieldListItem(item.data()['name']))
                  .toList(),
              onSuggestionTap: (searchItem) {
                Navigator.pushNamed(
                  context,
                  OrderScreen.routeName,
                  arguments: {
                    'item': state.foodList
                        .where((item) =>
                            item.data()['name'] == searchItem.searchKey)
                        .first,
                  },
                );
                _searchController.clear();
              },
              controller: _searchController,
              onSubmit: (p0) {
                Navigator.pushNamed(
                  context,
                  OrderScreen.routeName,
                  arguments: {
                    'item': state.foodList
                        .where((item) => item.data()['name'] == p0)
                        .first
                  },
                );
                _searchController.clear();
              },
              searchInputDecoration: InputDecoration(
                border: InputBorder.none,
                prefixIcon: Image.asset(
                  Helper.getAssetName("search_filled.png", "virtual"),
                ),
                hintStyle:
                    const TextStyle(color: AppColor.placeholder, fontSize: 18),
                contentPadding: const EdgeInsets.only(top: 17),
              ),
            ));
      },
    );
  }
}

 
```

this is what I did:

I had a simple SearchField with just 2 or 3 properties, they were working fine if you didn't touch the controller (initialize it). Once I initialized the controller (even with blank text) then try to hot reload or change the page (not push, pushReplacement) then I'd get this error that it's not mouted or something and the context can't be used.

Here's the STACK TRACE:



```Restarted application in 2,149ms.
W/DynamiteModule( 4776): Local module descriptor class for com.google.android.gms.providerinstaller.dynamite not found.
I/DynamiteModule( 4776): Considering local module com.google.android.gms.providerinstaller.dynamite:0 and remote module com.google.android.gms.providerinstaller.dynamite:0
W/ProviderInstaller( 4776): Failed to load providerinstaller module: No acceptable module com.google.android.gms.providerinstaller.dynamite found. Local version is 0 and remote version is 0.
Reloaded 1 of 1486 libraries in 632ms.
Reloaded 1 of 1486 libraries in 661ms.

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building StreamBuilder<List<SearchFieldListItem<dynamic>?>?>(dirty, state: _StreamBuilderBaseState<List<SearchFieldListItem<dynamic>?>?, AsyncSnapshot<List<SearchFieldListItem<dynamic>?>?>>#6a2d9):
This widget has been unmounted, so the State no longer has a context (and should be considered defunct).

Consider canceling any active work during "dispose" or using the "mounted" getter to determine if the State is still active.
The relevant error-causing widget was
ProgressHUD
When the exception was thrown, this was the stack
#0      State.context.<anonymous closure>
#1      State.context
#2      _SearchFieldState.getYOffset (package:searchfield/src/searchfield.dart:478:32)
#3      _SearchFieldState._createOverlay.<anonymous closure>.<anonymous closure> (package:searchfield/src/searchfield.dart:511:29)
#4      StreamBuilder.build
#5      _StreamBuilderBaseState.build
#6      StatefulElement.build
#7      ComponentElement.performRebuild
#8      StatefulElement.performRebuild
#9      Element.rebuild
#10     StatefulElement.update
#11     Element.updateChild
#12     ComponentElement.performRebuild
#13     Element.rebuild
#14     ProxyElement.update
#15     Element.updateChild
#16     ComponentElement.performRebuild
#17     StatefulElement.performRebuild
#18     Element.rebuild
#19     StatefulElement.update
#20     Element.updateChild
#21     ComponentElement.performRebuild
#22     StatefulElement.performRebuild
#23     Element.rebuild
#24     StatefulElement.update
#25     Element.updateChild
#26     RenderObjectElement.updateChildren
#27     MultiChildRenderObjectElement.update
#28     Element.updateChild
#29     ComponentElement.performRebuild
#30     StatefulElement.performRebuild
#31     Element.rebuild
#32     BuildOwner.buildScope
#33     WidgetsBinding.drawFrame
#34     RendererBinding._handlePersistentFrameCallback
#35     SchedulerBinding._invokeFrameCallback
#36     SchedulerBinding.handleDrawFrame
#37     SchedulerBinding._handleDrawFrame
#41     _invoke (dart:ui/hooks.dart:151:10)
#42     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#43     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
════════════════════════════════════════════════════════════════════════════════
```

**Comment by maheshmnj** [comment] 2022-07-30 07:23
Thanks for the code sample @fruitbite, As per my understanding when the widget is removed or added to widget tree this issue is reproduced. Can anyone who is facing this issue please test using this branch `fix-17`  by adding to `pubspec.yaml`

```yaml
  searchfield:
    git:
      url: https://github.com/maheshmnj/searchfield
      ref: fix-17
```
and see if the issue is fixed?

**Comment by maheshmnj** [comment] 2022-08-08 05:30
Update a new release is available  `searchfield: ^0.6.8` Can someone please confirm if this issue is fixed.

**Comment by maheshmnj** [comment] 2023-05-02 22:27
Since there has been no update on this issue for a while, I am going to close this issue if anyone still encounters this issue with the latest release of the package please feel free to write in the comments and I will reopen it.

cc: @anais6 

Thank you.

**Closed by maheshmnj** 2023-05-02 22:27 UTC
Labels: waiting for author, in triage

**Comment by klausgreiner** [comment] 2024-11-20 14:02
Platform macos
searchfield: 1.1.8
Flutter 3.24.3 
Tools • Dart 3.5.3 • DevTools 2.37.3

════════ Exception caught by foundation library ════════════════════════════════
This widget has been unmounted, so the State no longer has a context (and should be considered defunct).
════════════════════════════════════════════════════════════════════════════════
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Cannot add new events after calling 

════════ Exception caught by foundation library ════════════════════════════════
Bad state: Cannot add new events after calling close
════════════════════════════════════════════════════════════════════════════════

**Comment by maheshj01** [comment] 2024-11-20 16:34
@klausgreiner, please file a separate issue.
